Importação das bibliotecas

In [ ]:
from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')
drive.mount('/content/drive')


%matplotlib inline
%precision %.2f
pd.options.display.float_format = '{:,.2f}'.format

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [ ]:
df1 = pd.read_csv('/content/drive/My Drive/Codenation/Projeto/estaticos_portfolio1.csv')
df2 = pd.read_csv('/content/drive/My Drive/Codenation/Projeto/estaticos_portfolio2.csv')
df3 = pd.read_csv('/content/drive/My Drive/Codenation/Projeto/estaticos_portfolio3.csv')
df = pd.read_csv('/content/drive/My Drive/Codenation/Projeto/estaticos_market.csv')

In [ ]:
df.head()

   Unnamed: 0  ... qt_filiais
0           0  ...          0
1           1  ...          0
2           2  ...          0
3           3  ...          0
4           4  ...          0

[5 rows x 182 columns]

In [ ]:
def printa(dfs):
    aux = pd.DataFrame({'colunas': dfs.columns,
                    'tipos': dfs.dtypes,
                    'percentual_faltante': dfs.isna().sum() / dfs.shape[0]})
    return aux.values

In [ ]:
printa(df)

array([['Unnamed: 0', dtype('int64'), 0.0],
       ['id', dtype('O'), 0.0],
       ['fl_matriz', dtype('bool'), 0.0],
       ['de_natureza_juridica', dtype('O'), 0.0],
       ['sg_uf', dtype('O'), 0.0],
       ['natureza_juridica_macro', dtype('O'), 0.0],
       ['de_ramo', dtype('O'), 0.0],
       ['setor', dtype('O'), 0.004168307022742906],
       ['idade_empresa_anos', dtype('float64'), 0.0],
       ['idade_emp_cat', dtype('O'), 0.0],
       ['fl_me', dtype('bool'), 0.0],
       ['fl_sa', dtype('bool'), 0.0],
       ['fl_epp', dtype('bool'), 0.0],
       ['fl_mei', dtype('bool'), 0.0],
       ['fl_ltda', dtype('bool'), 0.0],
       ['dt_situacao', dtype('O'), 1.2978641482333906e-05],
       ['fl_st_especial', dtype('bool'), 0.0],
       ['fl_email', dtype('bool'), 0.0],
       ['fl_telefone', dtype('bool'), 0.0],
       ['fl_rm', dtype('O'), 0.0],
       ['nm_divisao', dtype('O'), 0.004168307022742906],
       ['nm_segmento', dtype('O'), 0.004168307022742906],
       ['fl_spa', dtype('O'), 0.004168307022742906],
       ['fl_antt', dtype('O'), 0.004168307022742906],
       ['fl_veiculo', dtype('O'), 0.004168307022742906],
       ['vl_total_tancagem', dtype('float64'), 0.9993943300641578],
       ['vl_total_veiculos_antt', dtype('float64'), 0.9996192931831849],
       ['vl_total_veiculos_leves', dtype('float64'), 0.9336272274593445],
       ['vl_total_veiculos_pesados', dtype('float64'),
        0.9336272274593445],
       ['fl_optante_simples', dtype('O'), 0.17891706215471406],
       ['qt_art', dtype('float64'), 0.98574512543857],
       ['vl_total_veiculos_pesados_grupo', dtype('float64'),
        0.004168307022742906],
       ['vl_total_veiculos_leves_grupo', dtype('float64'),
        0.004168307022742906],
       ['vl_total_tancagem_grupo', dtype('float64'), 0.9961929318318488],
       ['vl_total_veiculos_antt_grupo', dtype('float64'),
        0.9992731960769893],
       ['vl_potenc_cons_oleo_gas', dtype('float64'), 0.9920332772367607],
       ['fl_optante_simei', dtype('O'), 0.17891706215471406],
       ['sg_uf_matriz', dtype('O'), 0.0041942643057075735],
       ['de_saude_tributaria', dtype('O'), 0.03212430077569014],
       ['de_saude_rescencia', dtype('O'), 0.03212430077569014],
       ['nu_meses_rescencia', dtype('float64'), 0.09793682862569165],
       ['de_nivel_atividade', dtype('O'), 0.024157578012450845],
       ['de_indicador_telefone', dtype('O'), 0.9050547482359863],
       ['fl_simples_irregular', dtype('O'), 0.004168307022742906],
       ['vl_frota', dtype('float64'), 0.9476744437570571],
       ['empsetorcensitariofaixarendapopulacao', dtype('float64'),
        0.3111175042937672],
       ['nm_meso_regiao', dtype('O'), 0.1269700496216726],
       ['nm_micro_regiao', dtype('O'), 0.1269700496216726],
       ['fl_passivel_iss', dtype('O'), 0.004168307022742906],
       ['qt_socios', dtype('float64'), 0.24895413780721526],
       ['qt_socios_pf', dtype('float64'), 0.24895413780721526],
       ['qt_socios_pj', dtype('float64'), 0.24895413780721526],
       ['idade_media_socios', dtype('float64'), 0.3279313343341308],
       ['idade_maxima_socios', dtype('float64'), 0.3279313343341308],
       ['idade_minima_socios', dtype('float64'), 0.3279313343341308],
       ['qt_socios_st_regular', dtype('float64'), 0.33510203375312025],
       ['qt_socios_st_suspensa', dtype('float64'), 0.9929677394234887],
       ['qt_socios_masculino', dtype('float64'), 0.57794539452907],
       ['qt_socios_feminino', dtype('float64'), 0.686286767409766],
       ['qt_socios_pep', dtype('float64'), 0.9854141700807704],
       ['qt_alteracao_socio_total', dtype('float64'), 1.0],
       ['qt_alteracao_socio_90d', dtype('float64'), 1.0],
       ['qt_alteracao_socio_180d', dtype('float64'), 1.0],
       ['qt_alteracao_socio_365d', dtype('float64'), 1.0],
       ['qt_socios_pj_ativos', dtype('float64'), 0.9901708421840458],
       ['qt_socios_pj_nulos', dtype('float64'), 0.9901708421840458],
       ['qt_socios_pj_baixados', dtype('float64'), 0.9901708421840458],
       ['qt_socios_pj_suspensos', dtype('float64'), 0.9901708421840458],
       ['qt_socios_pj_inaptos', dtype('float64'), 0.9901708421840458],
       ['vl_idade_media_socios_pj', dtype('float64'), 0.9901708421840458],
       ['vl_idade_maxima_socios_pj', dtype('float64'),
        0.9901708421840458],
       ['vl_idade_minima_socios_pj', dtype('float64'),
        0.9901708421840458],
       ['qt_coligados', dtype('float64'), 0.8585522758047839],
       ['qt_socios_coligados', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_matriz', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_ativo', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_baixada', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_inapta', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_suspensa', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_nula', dtype('float64'), 0.8585522758047839],
       ['idade_media_coligadas', dtype('float64'), 0.8585522758047839],
       ['idade_maxima_coligadas', dtype('float64'), 0.8585522758047839],
       ['idade_minima_coligadas', dtype('float64'), 0.8585522758047839],
       ['coligada_mais_nova_ativa', dtype('float64'), 0.8590800738917321],
       ['coligada_mais_antiga_ativa', dtype('float64'),
        0.8590800738917321],
       ['idade_media_coligadas_ativas', dtype('float64'),
        0.8590800738917321],
       ['coligada_mais_nova_baixada', dtype('float64'),
        0.9997058174597337],
       ['coligada_mais_antiga_baixada', dtype('float64'),
        0.9997058174597337],
       ['idade_media_coligadas_baixadas', dtype('float64'),
        0.9997058174597337],
       ['qt_coligados_sa', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_me', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_mei', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_ltda', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_epp', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_norte', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_sul', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_nordeste', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_centro', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_sudeste', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_exterior', dtype('float64'), 0.8585522758047839],
       ['qt_ufs_coligados', dtype('float64'), 0.8585522758047839],
       ['qt_regioes_coligados', dtype('float64'), 0.8585522758047839],
       ['qt_ramos_coligados', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_industria', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_agropecuaria', dtype('float64'),
        0.8585522758047839],
       ['qt_coligados_comercio', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_serviço', dtype('float64'), 0.8585522758047839],
       ['qt_coligados_ccivil', dtype('float64'), 0.8585522758047839],
       ['qt_funcionarios_coligados', dtype('float64'),
        0.9084940882288048],
       ['qt_funcionarios_coligados_gp', dtype('float64'),
        0.9084940882288048],
       ['media_funcionarios_coligados_gp', dtype('float64'),
        0.9084940882288048],
       ['max_funcionarios_coligados_gp', dtype('float64'),
        0.9084940882288048],
       ['min_funcionarios_coligados_gp', dtype('float64'),
        0.9084940882288048],
       ['vl_folha_coligados', dtype('float64'), 0.9214489355350878],
       ['media_vl_folha_coligados', dtype('float64'), 0.9214489355350878],
       ['max_vl_folha_coligados', dtype('float64'), 0.9214489355350878],
       ['min_vl_folha_coligados', dtype('float64'), 0.9214489355350878],
       ['vl_folha_coligados_gp', dtype('float64'), 0.9209665626933277],
       ['media_vl_folha_coligados_gp', dtype('float64'),
        0.9209665626933277],
       ['max_vl_folha_coligados_gp', dtype('float64'),
        0.9209665626933277],
       ['min_vl_folha_coligados_gp', dtype('float64'),
        0.9209665626933277],
       ['faturamento_est_coligados', dtype('float64'),
        0.8604298526058949],
       ['media_faturamento_est_coligados', dtype('float64'),
        0.8604298526058949],
       ['max_faturamento_est_coligados', dtype('float64'),
        0.8604298526058949],
       ['min_faturamento_est_coligados', dtype('float64'),
        0.8604298526058949],
       ['faturamento_est_coligados_gp', dtype('float64'),
        0.8604298526058949],
       ['media_faturamento_est_coligados_gp', dtype('float64'),
        0.8604298526058949],
       ['max_faturamento_est_coligados_gp', dtype('float64'),
        0.8604298526058949],
       ['min_faturamento_est_coligados_gp', dtype('float64'),
        0.8604298526058949],
       ['total_filiais_coligados', dtype('float64'), 0.9558726189600647],
       ['media_filiais_coligados', dtype('float64'), 0.9558726189600647],
       ['max_filiais_coligados', dtype('float64'), 0.9558726189600647],
       ['min_filiais_coligados', dtype('float64'), 0.9558726189600647],
       ['qt_coligados_atividade_alto', dtype('float64'),
        0.8585522758047839],
       ['qt_coligados_atividade_medio', dtype('float64'),
        0.8585522758047839],
       ['qt_coligados_atividade_baixo', dtype('float64'),
        0.8585522758047839],
       ['qt_coligados_atividade_mt_baixo', dtype('float64'),
        0.8585522758047839],
       ['qt_coligados_atividade_inativo', dtype('float64'),
        0.8585522758047839],
       ['qt_coligadas', dtype('float64'), 0.8913449766168142],
       ['sum_faturamento_estimado_coligadas', dtype('float64'),
        0.8928310310665415],
       ['de_faixa_faturamento_estimado', dtype('O'),
        0.059513560517242124],
       ['de_faixa_faturamento_estimado_grupo', dtype('O'),
        0.059513560517242124],
       ['vl_faturamento_estimado_aux', dtype('float64'),
        0.059513560517242124],
       ['vl_faturamento_estimado_grupo_aux', dtype('float64'),
        0.059513560517242124],
       ['qt_ex_funcionarios', dtype('float64'), 0.750693275765848],
       ['qt_funcionarios_grupo', dtype('float64'), 0.7506738078036245],
       ['percent_func_genero_masc', dtype('float64'), 0.8357293347580997],
       ['percent_func_genero_fem', dtype('float64'), 0.8357293347580997],
       ['idade_ate_18', dtype('float64'), 0.9937140113087229],
       ['idade_de_19_a_23', dtype('float64'), 0.9439971620037292],
       ['idade_de_24_a_28', dtype('float64'), 0.9158659565907704],
       ['idade_de_29_a_33', dtype('float64'), 0.913166399162445],
       ['idade_de_34_a_38', dtype('float64'), 0.920551246165893],
       ['idade_de_39_a_43', dtype('float64'), 0.9342242449675318],
       ['idade_de_44_a_48', dtype('float64'), 0.9474581330656849],
       ['idade_de_49_a_53', dtype('float64'), 0.9588209336834682],
       ['idade_de_54_a_58', dtype('float64'), 0.9697705808807306],
       ['idade_acima_de_58', dtype('float64'), 0.9761495831692977],
       ['grau_instrucao_macro_analfabeto', dtype('float64'),
        0.9959247065745471],
       ['grau_instrucao_macro_escolaridade_fundamental',
        dtype('float64'), 0.9461472902759692],
       ['grau_instrucao_macro_escolaridade_media', dtype('float64'),
        0.853347840570368],
       ['grau_instrucao_macro_escolaridade_superior', dtype('float64'),
        0.9508390691718329],
       ['grau_instrucao_macro_desconhecido', dtype('float64'), 1.0],
       ['total', dtype('float64'), 0.8357293347580997],
       ['meses_ultima_contratacaco', dtype('float64'),
        0.7759583645181247],
       ['qt_admitidos_12meses', dtype('float64'), 0.7759583645181247],
       ['qt_desligados_12meses', dtype('float64'), 0.7759583645181247],
       ['qt_desligados', dtype('float64'), 0.7759583645181247],
       ['qt_admitidos', dtype('float64'), 0.7759583645181247],
       ['media_meses_servicos_all', dtype('float64'), 0.7759886480149167],
       ['max_meses_servicos_all', dtype('float64'), 0.7759886480149167],
       ['min_meses_servicos_all', dtype('float64'), 0.7759886480149167],
       ['media_meses_servicos', dtype('float64'), 0.8350393036526224],
       ['max_meses_servicos', dtype('float64'), 0.8350393036526224],
       ['min_meses_servicos', dtype('float64'), 0.8350393036526224],
       ['qt_funcionarios', dtype('float64'), 0.7759583645181247],
       ['qt_funcionarios_12meses', dtype('float64'), 0.7759583645181247],
       ['qt_funcionarios_24meses', dtype('float64'), 0.7759583645181247],
       ['tx_crescimento_12meses', dtype('float64'), 0.8401723563588854],
       ['tx_crescimento_24meses', dtype('float64'), 0.8398998048877564],
       ['tx_rotatividade', dtype('float64'), 0.7759583645181247],
       ['qt_filiais', dtype('int64'), 0.0]], dtype=object)